### ISSUE TITLE
could you help to provide a weight converter which can convert checking points from official TF-based ViT to PyTorch?

### ISSUE THREAD

**Issue by chaoyanghe** [jeonsworld/ViT-pytorch#1]
Nice work!

**Comment by jeonsworld** [comment]
The official source of the vision transformer is the jax/flax framework. The official source of the TF version has not been released. Let me know what the official TF means!!

**Comment by chaoyanghe** [comment]
> The official source of the vision transformer is the jax/flax framework. The official source of the TF version has not been released. Let me know what the official TF means!!

I mean the checking points released by the paper author.

**Comment by jeonsworld** [comment]
The code in the current repo automatically converts and loads the checkpoints provided by the author into pytorch weights.
There is no separate code for convert only, and I think it can be written by referring to section [modeling.py](https://github.com/jeonsworld/ViT-pytorch/blob/f4b6997d01b76069735a0ce15022f5bbeb0303d7/models/modeling.py#L266).

**Comment by chaoyanghe** [comment]
> The code in the current repo automatically converts and loads the checkpoints provided by the author into pytorch weights.
> There is no separate code for convert only, and I think it can be written by referring to section [modeling.py](https://github.com/jeonsworld/ViT-pytorch/blob/f4b6997d01b76069735a0ce15022f5bbeb0303d7/models/modeling.py#L266).

got it. Thanks. I sugges reorganizing the code and make this as a seperate class.

**Comment by jeonsworld** [comment]
Thanks for the good advice. Add it to my TODO list.
