### ISSUE TITLE
About imagenet-21k

### ISSUE THREAD

**Issue by zhangzjn** [jeonsworld/ViT-pytorch#10]
Thanks for your great repo !

I cannot find the link to download the imagenet-21k dataset, so is there any way to download Imagenet-21k now? Thanks a lot~

**Comment by jeonsworld** [comment]
I don't know how to get Imagenet-21k.
[This link](https://github.com/rwightman/pytorch-image-models/issues/277) will help you.

**Comment by apeterswu** [comment]
@zhangzjn hi, have you reproduced the imagenet result? Curious about that.
