### ISSUE TITLE
Low training speed on RTX 3090

### ISSUE THREAD

**Issue by lingorX** [jeonsworld/ViT-pytorch#18]
Training on the 3090 gets slower and slower as time goes on but the 2080ti doesn't have this problem

`torch                     1.8.0.dev20201130+cu110`
`torchvision               0.9.0.dev20201130+cu110`
`NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1`

**Comment by wilile26811249** [comment]
@0liliulei  Hi, you can train the vit on 2080ti? I tried to train the pretrained vit on 2080ti(11GB), but... CUDA out of memory. Are you use multi gpu or single?

**Comment by lingorX** [comment]
@wilile26811249 I use four cards to train vit_base_224_16

**Comment by wilile26811249** [comment]
Four 3090 or 2080ti?

**Comment by wilile26811249** [comment]
thank you. Have a nice day~

**Comment by longmalongma** [comment]
> @wilile26811249 I use four cards to train vit_base_224_16

Hi, how to use four cards to train vit_base_224_16? What is the training codes?
