### ISSUE TITLE
Model Architecture For Fine-tuning

### ISSUE THREAD

**Issue by chaoyanghe** [jeonsworld/ViT-pytorch#2]
In the original paper, the authors state that "**we remove the whole head (two linear layers) and replace it by a single, zero-initialized linear layer outputting the number of classes required by the target dataset.** We found this to be a little more robust than simply re-initializing the very last layer."

May I know which code snippet is related to this?

**Comment by jeonsworld** [comment]
Hi,
The zero-initialized linear layer can be checked in the following [code](https://github.com/jeonsworld/ViT-pytorch/blob/878ebc5bd12255d2fffd6c0257b83ee075607a79/models/modeling.py#L268). The zero-initialized linear layer is also used in Big Transfer (Bit) and shares one more related [link](https://github.com/google-research/big_transfer/issues/10).

**Comment by chaoyanghe** [comment]
OK. But where is removing two linear layers and replacing it by a single layer? I only see you zero-initialized a single linear layer.

**Comment by chaoyanghe** [comment]
Another issue is that you used the a Conv2d layer to extract features in the embedding layer. Is this hybrid architecture described in the original paper? Could you also support a version which does not rely on CNN?

**Comment by jeonsworld** [comment]
As far as I know, the two linear layers in the paper are the MLP layer whose activation function is tanh. You can check that part from the following [link](https://github.com/google-research/vision_transformer/blob/0040316f123353eaba186e7be914e58e656cc120/vit_jax/models.py#L248) (`pre_logits` and `head`).
Additionally, in this repository, we create a single linear layer that matches the target class without weight loads of `pre_logits` and `head`.

**Comment by jeonsworld** [comment]
As far as I know, the hybrid model replaces Conv2d with a different backbone. With a simple implementation you can remove Conv2d and use the BiT backbone for this part. Please refer to [timm](https://github.com/rwightman/pytorch-image-models/blob/80cd31f21f36142304d00d52799d0d06a97b30af/timm/models/vision_transformer.py#L169) for detailed implementation of hybrid model.

ViT used Conv2d for patch embedding, and I think not using CNN is a big challenge.

**Comment by chaoyanghe** [comment]
Please check Equation 1 in the original paper. That's the non-hybrid version.

**Comment by jeonsworld** [comment]
![image](https://user-images.githubusercontent.com/37530102/99516006-0abd1680-29d1-11eb-94a6-76f675fe0384.png)

The currently implemented part is the same as Equation (1).
Please refer to the following [link](https://github.com/jeonsworld/ViT-pytorch/blob/878ebc5bd12255d2fffd6c0257b83ee075607a79/models/modeling.py#L122) for the part about Equation (1).

**Comment by chaoyanghe** [comment]
Line 144         x = self.patch_embeddings(x)

self.patch_embeddings is conv2d?

**Comment by jeonsworld** [comment]
That's correct!
[Conv2d's](https://github.com/jeonsworld/ViT-pytorch/blob/878ebc5bd12255d2fffd6c0257b83ee075607a79/models/modeling.py#L131) kernel_size is the patch size.

**Comment by chaoyanghe** [comment]
@jeonsworld https://github.com/google-research/vision_transformer/blob/0040316f123353eaba186e7be914e58e656cc120/vit_jax/models.py#L215

Okay. Now I get your point. Look this comment. The author of ViT said s2d (sequence 2D) + embedding is equal to a Conv operation. I think this is the key. So, in essence, ViT is also CNN-based model. We cannot say we should give up CNN.

**Comment by jeonsworld** [comment]
Thanks for the nice comment. I think this gave me a better insight.
