### ISSUE TITLE
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)

### ISSUE THREAD

**Issue by yhangchen** [jeonsworld/ViT-pytorch#23]
Hi, by executing this
```bash
python3 train.py --name cifar10-100_500 --dataset cifar10 --model_type ViT-B_16 --pretrained_dir checkpoint/ViT-B_16.npz
```
I encounter the error:
```bash
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from apex import amp
  File "/home/tiger/.local/lib/python3.7/site-packages/apaex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```

**Comment by zhoufengfan** [comment]
I think you have install the wrong `apex`.
I have installed `apex` through the source code. You can refer to the official website and try again.

**Comment by airsimonhan** [comment]
git clone https://github.com/NVIDIA/apex
cd apex
python setup.py install

**Comment by jhq1234** [comment]
> git clone https://github.com/NVIDIA/apex cd apex python setup.py install

it works for me!
Thanks!

**Comment by luomi16** [comment]
!git clone https://github.com/NVIDIA/apex
!cd apex
!pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./

**Comment by luomi16** [comment]
!git clone https://github.com/NVIDIA/apex
%cd apex
!pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation ./

**Comment by QQQ796** [comment]
git clone https://github.com/NVIDIA/apex
cd apex
python setup.py install
these results fatal: destination path 'apex' already exists and is not an empty directory.
python3: can't open file '/content/drive/MyDrive/UGDRE-main/setup.py': [Errno 2] No such file or director.
How to do next??

**Comment by WangJianQ-0118** [comment]
> > git clone https://github.com/NVIDIA/apex cd apex python setup.py install
> 
> it works for me! Thanks!

华为昇腾910b也是安装英伟达的吗

**Comment by new-TonyWang** [comment]
> > > git clone https://github.com/NVIDIA/apex cd apex python setup.py install
> > 
> > 
> > it works for me! Thanks!
> 
> 华为昇腾910b也是安装英伟达的吗
用这个 https://gitee.com/ascend/apex.git
