### ISSUE TITLE
Request for pre-trained weights only on Imagenet2012.

### ISSUE THREAD

**Issue by JingyeChen** [jeonsworld/ViT-pytorch#27]
Thanks for your hard work! I wonder if there are some pre-trained weights only using Imagenet2012?  I found that the pre-trained ResNet provided by torchvision may be pre-trained only on Imagenet2012 so I want to take ViT and ResNet for a fair comparison.

**Comment by jeonsworld** [comment]
Unfortunately, the weights for pre-training in imagenet2012 were not disclosed.
Currently published weights are [pretrained-imagenet21k](https://console.cloud.google.com/storage/browser/vit_models/imagenet21k?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false), [pretrained-imagenet21k and finetuned-imagenet2012](https://console.cloud.google.com/storage/browser/vit_models/imagenet21k%2Bimagenet2012?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false).

**Comment by JingyeChen** [comment]
I got it. Thank you for your reply :D
