### ISSUE TITLE
how you save tensorboard?

### ISSUE THREAD

**Issue by seyeeet** [jeonsworld/ViT-pytorch#32]
@jeonsworld 
okay this is completely different questions, but I should ask it because i have not seen it anywhere else.
how did you save tensorboard so we can just click on it and see it? I want to do it as well. should I save it in some format or do anything special? please direct me to any link/material that can help me with that.
Thanks :)

**Comment by lorenzwu** [comment]
On default the tensorboard writer outputs the logs into the ./logs/{name of your run you sepcified with --name}/ directory.
If you have tensorboard installed you can just run:
`tensorboard --logdir=./logs/{name of your run}` (assuming you are currently in the ViT-pytorch dir)

For more information on tensorboard with pytorch check out this [tutorial](https://pytorch.org/tutorials/recipes/recipes/tensorboard_with_pytorch.html?highlight=tensorboard) by pytorch:

**Comment by seyeeet** [comment]
@lorenzwu thanks for trying to answer, but your answer is not correct.
As I mentioned I already very familiar with tb. 
My question was how he shows his tb freely to everyone that easily.
The answer is via https://tensorboard.dev/#get-started

**Comment by lorenzwu** [comment]
Oops. I'm sorry about that. Seems like I misunderstood the "how did you save tensorboard" part.
I didn't know you were talking about a link in the readme and not tensorboard as an application.
