### ISSUE TITLE
The Encoder implementation is different from the original "Attention is all need" paper?

### ISSUE THREAD

**Issue by chaoyanghe** [jeonsworld/ViT-pytorch#5]
Hi, I checked your code at https://github.com/jeonsworld/ViT-pytorch/blob/878ebc5bd12255d2fffd6c0257b83ee075607a79/models/modeling.py#L154.

Your implementation is: Attention(LayerNorm(x)) + x, but the original Transformer is: LayerNorm(x +Attention(x)). Is this an error or deliberately implemented like this?

**Comment by jeonsworld** [comment]
As in paper [On Layer Normalization in the Transformer Architecture](https://arxiv.org/abs/2002.04745), the location of LayerNormalization is generally used as pre-LN and post-LN. For example, Transformer Encoder-based BERT uses post-LN, but Vision Transformer uses pre-LN.
In conclusion, that implementation is correct.

**Comment by jeonsworld** [comment]
Additional comments.
[Attention is all you need](https://arxiv.org/abs/1706.03762) uses post-LN.

**Comment by jeonsworld** [comment]
I believe the issue has been answered and close the issue.

**Comment by chaoyanghe** [comment]
Thank you!
