### ISSUE TITLE
how can I use the output .bin file again ?

### ISSUE THREAD

**Issue by mohammedkw11** [jeonsworld/ViT-pytorch#53]
Hi,

Thank you for sharing this great work!

I want to use .bin file again. how I can do that.

Best,
Mohammed

**Comment by deepankarvarma** [comment]
Did you do that @mohammedkw11 , if yes can you please share the notebook link?

**Comment by Zhenyu001225** [comment]
> Did you do that @mohammedkw11 , if yes can you please share the notebook link?

Try to revise the setup function:
Revise:
    model.load_from(np.load(args.pretrained_dir))
To:
    state_dict = torch.load(args.pretrained_dir, map_location='cuda')
    model.load_state_dict(state_dict, strict=False)
