### ISSUE TITLE
Multi-GPU

### ISSUE THREAD

**Issue by kamalkraj** [jeonsworld/ViT-pytorch#8]
How to do multi-GPU training?
Now only one GPU get utilised 
<img width="799" alt="Screenshot 2020-12-29 at 9 27 49 PM" src="https://user-images.githubusercontent.com/17096858/103296803-e1a29380-4a1c-11eb-84fb-d7bd63a683cd.png">

**Comment by chanhoeom** [comment]
How did you solve this issue?

**Comment by chanhoeom** [comment]
> How to do multi-GPU training?
> Now only one GPU get utilised
> <img alt="Screenshot 2020-12-29 at 9 27 49 PM" width="799" src="https://user-images.githubusercontent.com/17096858/103296803-e1a29380-4a1c-11eb-84fb-d7bd63a683cd.png">

How did you solve this issue?

**Comment by TitaniumOne** [comment]
@kamalkraj @chanhoeom 
Hello, I meet the same issue, have you solved it?

**Comment by kamalkraj** [comment]
@TitaniumOne Checkout PyTorch distributed training
Pytorch multiprocess launcher script, [torch.distributed.launch](https://pytorch.org/docs/master/distributed.html#launch-utility)

**Comment by KleinXin** [comment]
Same problem even though using torch.distributed.launch, codes are shown below

CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --nproc_per_node=4 train.py xxx

It is weird that all the trainning are running on the first GPU. Then if the batch size is increased, OOM error is reported.

I was running the program in a docker container.

Any one knows what's wrong?

**Comment by cissoidx** [comment]
same error here

**Comment by hassanbabaie** [comment]
this might help:

https://github.com/jeonsworld/ViT-pytorch/issues/58
